// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1fmF5AxFjF2UJIl0wsSohlDtkc9IJF1s',
    appId: '1:682501623659:web:ee9db14935b07cf71a862e',
    messagingSenderId: '682501623659',
    projectId: 'hotel-c44d3',
    authDomain: 'hotel-c44d3.firebaseapp.com',
    storageBucket: 'hotel-c44d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLrSRt5L9ah4yH8aRWTvwvHI2NDjFhyMs',
    appId: '1:682501623659:android:d3c52d0dfa0a9b781a862e',
    messagingSenderId: '682501623659',
    projectId: 'hotel-c44d3',
    storageBucket: 'hotel-c44d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_gEF33zy4TMQMQcy8t-npT1eMEvfJK8c',
    appId: '1:682501623659:ios:4edab2271a80199a1a862e',
    messagingSenderId: '682501623659',
    projectId: 'hotel-c44d3',
    storageBucket: 'hotel-c44d3.firebasestorage.app',
    iosBundleId: 'com.example.paHasbi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_gEF33zy4TMQMQcy8t-npT1eMEvfJK8c',
    appId: '1:682501623659:ios:4edab2271a80199a1a862e',
    messagingSenderId: '682501623659',
    projectId: 'hotel-c44d3',
    storageBucket: 'hotel-c44d3.firebasestorage.app',
    iosBundleId: 'com.example.paHasbi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1fmF5AxFjF2UJIl0wsSohlDtkc9IJF1s',
    appId: '1:682501623659:web:30dfe39c7b18c4571a862e',
    messagingSenderId: '682501623659',
    projectId: 'hotel-c44d3',
    authDomain: 'hotel-c44d3.firebaseapp.com',
    storageBucket: 'hotel-c44d3.firebasestorage.app',
  );
}
